CREATE TABLE generals (
  no int(11) NOT NULL,
  name varchar(10) DEFAULT NULL,
  owner varchar(4) DEFAULT NULL,
  place varchar(8) DEFAULT NULL,
  status varchar(8) DEFAULT NULL,
  control int(3) DEFAULT 0,
  power int(3) DEFAULT 0,
  intelligence int(3) DEFAULT 0,
  politics int(3) DEFAULT 0,
  glamour int(3) DEFAULT 0,
  sex varchar(2) DEFAULT NULL,
  on_stage_year int(3) DEFAULT 0,
  birth_year int(3) DEFAULT 0,
  dead_year int(3) DEFAULT 0,
  gunnery_fitness varchar(1) DEFAULT NULL,
  halberd_fitness varchar(1) DEFAULT NULL,
  crossbowman_fitness varchar(1) DEFAULT NULL,
  cavalryman_fitness varchar(1) DEFAULT NULL,
  weaponry_fitness varchar(1) DEFAULT NULL,
  navy_fitness varchar(1) DEFAULT NULL,
  skill varchar(4) DEFAULT NULL,
  PRIMARY KEY (no)
)